# Users
USERS = [
    {
        'username': 'mhhasani',
        'first_name': 'mohammadhosein',
        'last_name': 'hasani',
        'password': '1234',
        'email': 'hasanimohammadhosein@gmail.com',
        'is_email_verified': True,
        'is_Artist': True,
        'birthday': '2002-09-18',
        'country': 'Iran',
        'city': 'Tehran',
        'image': '/media/profiles/photos/mhhasani.jpg',
    },
    {
        'username': 'melika',
        'first_name': 'melika',
        'last_name': 'mohammadi',
        'password': '1234',
        'email': 'melikamfakhar@gmail.com',
        'is_email_verified': True,
        'is_Artist': True,
        'birthday': '2002-11-20',
        'country': 'Iran',
        'city': 'Qom',
        'image': '/media/profiles/photos/melika.jpg',
    },
    {
        'username': 'zahra',
        'first_name': 'zahra',
        'last_name': 'tabatabaei',
        'password': '1234',
        'email': 'zahrasadat@gmail.com',
        'is_email_verified': True,
        'is_Artist': True,
        'birthday': '2002-09-16',
        'country': 'Iran',
        'city': 'Tehran',
        'image': '/media/profiles/photos/zahra.jpg',
    },
    {
        'username': 'maryam',
        'first_name': 'maryam',
        'last_name': 'jafari',
        'password': '1234',
        'email': 'maryamjafari@gmail.com',
        'is_email_verified': True,
        'is_Artist': True,
        'birthday': '2002-09-11',
        'country': 'Iran',
        'city': 'Yazd',
        'image': '/media/profiles/photos/maryam.jpg',
    },
    {
        'username': 'mojtaba',
        'first_name': 'mojtaba',
        'last_name': 'janbaz',
        'password': '1234',
        'email': 'mojtabajanbaz@gmail.com',
        'is_email_verified': True,
        'is_Artist': True,
        'birthday': '2002-08-27',
        'country': 'Iran',
        'city': 'Mazandaran',
        'image': '/media/profiles/photos/mojtaba.jpg',
    },
    {
        'username': 'amirmohammad',
        'first_name': 'amirmohammad',
        'last_name': 'khorshidi',
        'password': '1234',
        'email': 'amirmohammadkhorshidi@gmail.com',
        'is_email_verified': True,
        'is_Artist': True,
        'birthday': '2002-03-26',
        'country': 'Iran',
        'city': 'Tehran',
        'image': '/media/profiles/photos/amirmohammad.jpg',
    },
]
